language: generic
sudo: required
services:
  - docker

before_install:
  - pwd
  - ls -a
  - docker build -t samrjack/docker-workflow-test -f Dockerfile.dev .
    
script:
  - docker run -e CI=true samrjack/docker-workflow-test npm run test


