language: generic
sudo: required
services:
  - docker

before_install:
  - pwd
  - ls -a
  - docker build -t samrjack/docker-workflow-test -f Dockerfile.dev .
    
script:
  - docker run -e CI=true samrjack/docker-workflow-test npm run test

# Won't actually use since I don't have an AWS account
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-workflow-test"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-#########"
  bucket_path: "docker-workflow-test"
  on:
    branch: main-prod
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
